-- Generated by vault-agent (WP36, ADR-0013): surrogate→natural-key translation for
-- the link staged by 'stg_bill_of_materials'.
-- 'BillOfMaterials' references 'Product.ProductID', a surrogate; the hub is keyed on 'PRODUCTNUMBER', the natural key.
-- 'BillOfMaterials' references 'Product.ProductID', a surrogate; the hub is keyed on 'PRODUCTNUMBER', the natural key.
-- This view joins the natural key(s) in so the stage model can hash the link from
-- them. LEFT JOIN: every source row survives; an unmatched surrogate becomes a NULL
-- natural key, which stg_bill_of_materials_via_product_and_product.yml's not_null test refuses at build time. The
-- translation is visible here, never hidden in a mapping.
{{ config(materialized='view') }}

select t.*, r1.PRODUCTNUMBER as ASSEMBLY_PRODUCTNUMBER, r2.PRODUCTNUMBER as COMPONENT_PRODUCTNUMBER
from {{ ref('BillOfMaterials') }} t
left join {{ ref('Product') }} r1 on t.PRODUCTASSEMBLYID = r1.PRODUCTID
left join {{ ref('Product') }} r2 on t.COMPONENTID = r2.PRODUCTID
