-- Generated by vault-agent (WP36, ADR-0013): surrogate→natural-key translation for
-- the link staged by 'stg_sales_person_quota_history'.
-- 'SalesPersonQuotaHistory' references 'Employee.BusinessEntityID', a surrogate; the hub is keyed on 'NATIONALIDNUMBER', the natural key.
-- This view joins the natural key(s) in so the stage model can hash the link from
-- them. LEFT JOIN: every source row survives; an unmatched surrogate becomes a NULL
-- natural key, which stg_sales_person_quota_history_via_employee.yml's not_null test refuses at build time. The
-- translation is visible here, never hidden in a mapping.
{{ config(materialized='view') }}

select t.*, r.NATIONALIDNUMBER as NATIONALIDNUMBER
from {{ ref('SalesPersonQuotaHistory') }} t
left join {{ ref('Employee') }} r on t.BUSINESSENTITYID = r.BUSINESSENTITYID
