-- Generated by vault-agent (WP36, ADR-0013): surrogate→natural-key translation for
-- the link staged by 'stg_sales_order_line'.
-- 'SalesOrderDetail' references 'SalesOrderHeader.SalesOrderID', a surrogate; the hub is keyed on 'SALESORDERNUMBER', the natural key.
-- 'SalesOrderDetail' references 'Product.ProductID', a surrogate; the hub is keyed on 'PRODUCTNUMBER', the natural key.
-- This view joins the natural key(s) in so the stage model can hash the link from
-- them. LEFT JOIN: every source row survives; an unmatched surrogate becomes a NULL
-- natural key, which stg_sales_order_line_via_salesorderheader_and_product.yml's not_null test refuses at build time. The
-- translation is visible here, never hidden in a mapping.
{{ config(materialized='view') }}

select t.*, r1.SALESORDERNUMBER as SALESORDERNUMBER, r2.PRODUCTNUMBER as PRODUCTNUMBER
from {{ ref('SalesOrderDetail') }} t
left join {{ ref('SalesOrderHeader') }} r1 on t.SALESORDERID = r1.SALESORDERID
left join {{ ref('Product') }} r2 on t.PRODUCTID = r2.PRODUCTID
