-- Generated by vault-agent (WP36, ADR-0013): surrogate→natural-key translation for
-- the link staged by 'stg_shopping_cart_item_product'.
-- 'ShoppingCartItem' references 'Product.ProductID', a surrogate; the hub is keyed on 'PRODUCTNUMBER', the natural key.
-- This view joins the natural key(s) in so the stage model can hash the link from
-- them. LEFT JOIN: every source row survives; an unmatched surrogate becomes a NULL
-- natural key, which stg_shopping_cart_item_product_via_product.yml's not_null test refuses at build time. The
-- translation is visible here, never hidden in a mapping.
{{ config(materialized='view') }}

select t.*, r.PRODUCTNUMBER as PRODUCTNUMBER
from {{ ref('ShoppingCartItem') }} t
left join {{ ref('Product') }} r on t.PRODUCTID = r.PRODUCTID
