-- Generated by vault-agent (WP36, ADR-0013): surrogate→natural-key translation for
-- the link staged by 'stg_location_capacity_history'.
-- 'LocationCapacityHistory' references 'Location.LocationID', a surrogate; the hub is keyed on 'NAME', the natural key.
-- This view joins the natural key(s) in so the stage model can hash the link from
-- them. LEFT JOIN: every source row survives; an unmatched surrogate becomes a NULL
-- natural key, which stg_location_capacity_history_via_location.yml's not_null test refuses at build time. The
-- translation is visible here, never hidden in a mapping.
{{ config(materialized='view') }}

select t.*, r.NAME as NAME
from {{ ref('LocationCapacityHistory') }} t
left join {{ ref('Location') }} r on t.LOCATIONID = r.LOCATIONID
