-- Generated by vault-agent (WP36, ADR-0013): surrogate→natural-key translation for
-- the link staged by 'stg_product_inventory'.
-- 'ProductInventory' references 'Product.ProductID', a surrogate; the hub is keyed on 'PRODUCTNUMBER', the natural key.
-- 'ProductInventory' references 'Location.LocationID', a surrogate; the hub is keyed on 'NAME', the natural key.
-- This view joins the natural key(s) in so the stage model can hash the link from
-- them. LEFT JOIN: every source row survives; an unmatched surrogate becomes a NULL
-- natural key, which stg_product_inventory_via_product_and_location.yml's not_null test refuses at build time. The
-- translation is visible here, never hidden in a mapping.
{{ config(materialized='view') }}

select t.*, r1.PRODUCTNUMBER as PRODUCTNUMBER, r2.NAME as NAME
from {{ ref('ProductInventory') }} t
left join {{ ref('Product') }} r1 on t.PRODUCTID = r1.PRODUCTID
left join {{ ref('Location') }} r2 on t.LOCATIONID = r2.LOCATIONID
